# Generated by Django 5.2.11 on 2026-04-20 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('code', models.CharField(help_text='County code e.g. NRB', max_length=5, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=200.0, max_digits=8)),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PickupStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('address', models.CharField(max_length=300)),
                ('town', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('pickup_fee', models.DecimalField(decimal_places=2, default=100.0, max_digits=8)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('operating_hours', models.CharField(default='Mon-Sat: 8AM - 6PM', max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_stations', to='pickups.county')),
            ],
            options={
                'ordering': ['county__name', 'name'],
            },
        ),
    ]
